export {default as Material} from "./material/Material.ts"
export {default as Categorical} from "./material/Categorical.ts"
export {default as Nominal} from "./material/Nominal.ts"
export {default as Numerical} from "./material/Numerical.ts"
export {default as NumericalTuple} from "./material/NumericalTuple.ts"