export { default as birthdate } from "./birthdate/mod.ts"
export { default as bloodType } from "./bloodType/mod.ts"
export { default as gender } from "./gender/mod.ts"
export { default as name } from "./name/mod.ts"
export { default as residence } from "./residence/mod.ts"
export { default as school } from "./school/mod.ts"
export { default as size } from "./size/mod.ts"
export { default as surname } from "./surname/mod.ts"